// Generated by CoffeeScript 1.4.0
(function() {
  var Formwatcher, ace, o,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  o = require("jquery");

  Formwatcher = require("formwatcher");

  ace = require("./ace.js");

  Formwatcher.decorators.push((function(_super) {

    __extends(_Class, _super);

    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    _Class.prototype.name = "Ace";

    _Class.prototype.description = "Turns a textarea into the ace editor.";

    _Class.prototype.nodeNames = ["TEXTAREA"];

    _Class.prototype.classNames = ["ace"];

    _Class.prototype.decorate = function(input) {
      var $aceContainer, $input, aceContainer, editor, elements;
      elements = {
        input: input
      };
      $input = o(input);
      $input.hide();
      $aceContainer = o("<div class=\"formwatcher-ace-editor\"></div>");
      aceContainer = $aceContainer.get(0);
      elements.ace = aceContainer;
      editor = ace.edit(aceContainer);
      editor.getSession().setMode("ace/mode/javascript");
      return elements;
    };

    return _Class;

  })(Formwatcher.Decorator));

}).call(this);
