// Generated by CoffeeScript 1.4.0
(function() {
  var Formwatcher, o,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  o = require("jquery");

  Formwatcher = require("formwatcher");

  Formwatcher.registerDecorator((function(_super) {

    __extends(_Class, _super);

    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    _Class.prototype.name = "Ace";

    _Class.prototype.description = "Turns a textarea into the ace editor.";

    _Class.prototype.nodeNames = ["TEXTAREA"];

    _Class.prototype.classNames = ["ace"];

    _Class.prototype.defaultOptions = {
      theme: null,
      mode: null,
      tabSize: 2,
      softTabs: true
    };

    _Class.prototype.decorate = function(input) {
      var $aceContainerElement, $aceElement, $input, aceElement, editor, elements;
      elements = {
        input: input
      };
      $input = o(input);
      $input.hide();
      $aceContainerElement = o("<div class=\"formwatcher-ace-container\"></div>");
      $aceElement = o("<div class=\"formwatcher-ace-editor\"></div>");
      $aceContainerElement.append($aceElement);
      $aceContainerElement.insertAfter($input);
      aceElement = $aceElement.get(0);
      elements.ace = aceElement;
      editor = window.ace.edit(aceElement);
      editor.setValue($input.val());
      editor.getSession().setTabSize(this.options.tabSize);
      editor.getSession().setUseSoftTabs(this.options.softTabs);
      return elements;
    };

    return _Class;

  })(Formwatcher.Decorator));

}).call(this);
